#pragma once

enum class AttenuationTag {
	NONE,
	NORMAL_ATTACK,
	ELEMENTAL_BURST_EXTRA,

	HYDRO_DAMAGE,
	PYRO_DAMAGE,
	ELECTRO_DAMAGE,

	FOUL_LEGACY,
	RIPTIDE,
	CHARGED_ATTACK,

	ELEMENTAL_SKILL,
	ELEMENTAL_SKILL_ANEMO,
	ELEMENTAL_SKILL_CRYO,
	ELEMENTAL_SKILL_ELECTRO,
	ELEMENTAL_SKILL_HYDRO,
	ELEMENTAL_SKILL_PYRO,
	
	ELEMENTAL_BURST,
	ELEMENTAL_BURST_CRYO,
	ELEMENTAL_BURST_ELECTRO,
	ELEMENTAL_BURST_HYDRO,
	ELEMENTAL_BURST_PYRO,

	WAKE_OF_EARTH,
	ILLUSORY_TORRENT,
};
